services:
  lotus:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILD_TARGET=${LOTUS_BUILD_TARGET}
    user: "10000"
    stop_grace_period: 1m
    image: lotus:local
    pull_policy: never
    volumes: 
      - filecoin-data:/home/filecoin/.lotus
    ports:
      - 6665:6665/tcp
    environment:
      - LOTUS_FVM_CONCURRENCY=${FVM_CONCURRENCY:-4}
      - LOTUS_FVM_CONCURRENCY_RESERVED=4
    entrypoint:
       - docker-entrypoint.sh
    labels:
      - traefik.enable=true
      - traefik.http.routers.lotus.service=lotus
      - traefik.http.routers.lotus.entrypoints=websecure
      - traefik.http.routers.lotus.rule=Host(`${RPC_HOST}.${DOMAIN}`)
      - traefik.http.routers.lotus.tls.certresolver=letsencrypt
      - traefik.http.routers.lotuslb.service=lotus
      - traefik.http.routers.lotuslb.entrypoints=websecure
      - traefik.http.routers.lotuslb.rule=Host(`${RPC_LB}.${DOMAIN}`)
      - traefik.http.routers.lotuslb.tls.certresolver=letsencrypt
      - traefik.http.services.lotus.loadbalancer.server.port=1234

volumes:
  filecoin-data:
